// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3I2IHLaNPijjkf9pNRXEPYSrNu7h0iQ',
    appId: '1:380383353541:web:787c802552c085dcbe6eac',
    messagingSenderId: '380383353541',
    projectId: 'mycv-b5010',
    authDomain: 'mycv-b5010.firebaseapp.com',
    databaseURL: 'https://mycv-b5010-default-rtdb.firebaseio.com',
    storageBucket: 'mycv-b5010.firebasestorage.app',
    measurementId: 'G-LJQHMF264N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhys0eXQyTxDvGHjHnt_RBPQ43A7s45VI',
    appId: '1:380383353541:android:b36bc39b7e19512bbe6eac',
    messagingSenderId: '380383353541',
    projectId: 'mycv-b5010',
    databaseURL: 'https://mycv-b5010-default-rtdb.firebaseio.com',
    storageBucket: 'mycv-b5010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-MaOofkJ911hN1Pciofdt9tnf-cEvUuI',
    appId: '1:380383353541:ios:04f07c1f1db3f96ebe6eac',
    messagingSenderId: '380383353541',
    projectId: 'mycv-b5010',
    databaseURL: 'https://mycv-b5010-default-rtdb.firebaseio.com',
    storageBucket: 'mycv-b5010.firebasestorage.app',
    iosBundleId: 'com.example.cv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-MaOofkJ911hN1Pciofdt9tnf-cEvUuI',
    appId: '1:380383353541:ios:04f07c1f1db3f96ebe6eac',
    messagingSenderId: '380383353541',
    projectId: 'mycv-b5010',
    databaseURL: 'https://mycv-b5010-default-rtdb.firebaseio.com',
    storageBucket: 'mycv-b5010.firebasestorage.app',
    iosBundleId: 'com.example.cv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3I2IHLaNPijjkf9pNRXEPYSrNu7h0iQ',
    appId: '1:380383353541:web:c3f1012d58ce2546be6eac',
    messagingSenderId: '380383353541',
    projectId: 'mycv-b5010',
    authDomain: 'mycv-b5010.firebaseapp.com',
    databaseURL: 'https://mycv-b5010-default-rtdb.firebaseio.com',
    storageBucket: 'mycv-b5010.firebasestorage.app',
    measurementId: 'G-TPN16QVTCJ',
  );

}